BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "tags" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "medias" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"checksum"	TEXT NOT NULL,
	"note"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "media_tags" (
	"media_id"	INTEGER,
	"tag_id"	INTEGER,
	PRIMARY KEY("tag_id","media_id")
);
COMMIT;
